// THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
// BY HAND!!
//
// Generated by lcm-gen

#include <string.h>
#include "grid_map_t.h"

static int __grid_map_t_hash_computed;
static uint64_t __grid_map_t_hash;

uint64_t __grid_map_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __grid_map_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent =  p;
    cp.v = (void*)__grid_map_t_get_hash;
    (void) cp;

    uint64_t hash = (uint64_t)0x3b95cdd95c1cd816LL
         + __int64_t_hash_recursive(&cp)
         + __int8_t_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __byte_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __grid_map_t_get_hash(void)
{
    if (!__grid_map_t_hash_computed) {
        __grid_map_t_hash = (int64_t)__grid_map_t_hash_recursive(NULL);
        __grid_map_t_hash_computed = 1;
    }

    return __grid_map_t_hash;
}

int __grid_map_t_encode_array(void *buf, int offset, int maxlen, const grid_map_t *p, int elements)
{
    int pos = 0, element;
    int thislen;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].encoding), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].x0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].y0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].meters_per_pixel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].datalen), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].src), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __byte_encode_array(buf, offset + pos, maxlen - pos, p[element].dst, p[element].datalen);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int grid_map_t_encode(void *buf, int offset, int maxlen, const grid_map_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __grid_map_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __grid_map_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __grid_map_t_encoded_array_size(const grid_map_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].utime), 1);

        size += __int8_t_encoded_array_size(&(p[element].encoding), 1);

        size += __double_encoded_array_size(&(p[element].x0), 1);

        size += __double_encoded_array_size(&(p[element].y0), 1);

        size += __double_encoded_array_size(&(p[element].meters_per_pixel), 1);

        size += __int32_t_encoded_array_size(&(p[element].width), 1);

        size += __int32_t_encoded_array_size(&(p[element].height), 1);

        size += __int32_t_encoded_array_size(&(p[element].datalen), 1);

        size += __string_encoded_array_size(&(p[element].src), 1);

        size += __byte_encoded_array_size(p[element].dst, p[element].datalen);

    }
    return size;
}

int grid_map_t_encoded_size(const grid_map_t *p)
{
    return 8 + __grid_map_t_encoded_array_size(p, 1);
}

int __grid_map_t_decode_array(const void *buf, int offset, int maxlen, grid_map_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].utime), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].encoding), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].x0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].y0), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].meters_per_pixel), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].width), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].height), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].datalen), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].src), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].dst = (uint8_t*) lcm_malloc(sizeof(uint8_t) * p[element].datalen);
        thislen = __byte_decode_array(buf, offset + pos, maxlen - pos, p[element].dst, p[element].datalen);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __grid_map_t_decode_array_cleanup(grid_map_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].utime), 1);

        __int8_t_decode_array_cleanup(&(p[element].encoding), 1);

        __double_decode_array_cleanup(&(p[element].x0), 1);

        __double_decode_array_cleanup(&(p[element].y0), 1);

        __double_decode_array_cleanup(&(p[element].meters_per_pixel), 1);

        __int32_t_decode_array_cleanup(&(p[element].width), 1);

        __int32_t_decode_array_cleanup(&(p[element].height), 1);

        __int32_t_decode_array_cleanup(&(p[element].datalen), 1);

        __string_decode_array_cleanup(&(p[element].src), 1);

        __byte_decode_array_cleanup(p[element].dst, p[element].datalen);
        if (p[element].dst) free(p[element].dst);

    }
    return 0;
}

int grid_map_t_decode(const void *buf, int offset, int maxlen, grid_map_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __grid_map_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __grid_map_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int grid_map_t_decode_cleanup(grid_map_t *p)
{
    return __grid_map_t_decode_array_cleanup(p, 1);
}

int __grid_map_t_clone_array(const grid_map_t *p, grid_map_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].utime), &(q[element].utime), 1);

        __int8_t_clone_array(&(p[element].encoding), &(q[element].encoding), 1);

        __double_clone_array(&(p[element].x0), &(q[element].x0), 1);

        __double_clone_array(&(p[element].y0), &(q[element].y0), 1);

        __double_clone_array(&(p[element].meters_per_pixel), &(q[element].meters_per_pixel), 1);

        __int32_t_clone_array(&(p[element].width), &(q[element].width), 1);

        __int32_t_clone_array(&(p[element].height), &(q[element].height), 1);

        __int32_t_clone_array(&(p[element].datalen), &(q[element].datalen), 1);

        __string_clone_array(&(p[element].src), &(q[element].src), 1);

        q[element].dst = (uint8_t*) lcm_malloc(sizeof(uint8_t) * q[element].datalen);
        __byte_clone_array(p[element].dst, q[element].dst, p[element].datalen);

    }
    return 0;
}

grid_map_t *grid_map_t_copy(const grid_map_t *p)
{
    grid_map_t *q = (grid_map_t*) malloc(sizeof(grid_map_t));
    __grid_map_t_clone_array(p, q, 1);
    return q;
}

void grid_map_t_destroy(grid_map_t *p)
{
    __grid_map_t_decode_array_cleanup(p, 1);
    free(p);
}

int grid_map_t_publish(lcm_t *lc, const char *channel, const grid_map_t *p)
{
      int max_data_size = grid_map_t_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = grid_map_t_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _grid_map_t_subscription_t {
    grid_map_t_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void grid_map_t_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    grid_map_t p;
    memset(&p, 0, sizeof(grid_map_t));
    status = grid_map_t_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding grid_map_t!!!\n", status);
        return;
    }

    grid_map_t_subscription_t *h = (grid_map_t_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    grid_map_t_decode_cleanup (&p);
}

grid_map_t_subscription_t* grid_map_t_subscribe (lcm_t *lcm,
                    const char *channel,
                    grid_map_t_handler_t f, void *userdata)
{
    grid_map_t_subscription_t *n = (grid_map_t_subscription_t*)
                       malloc(sizeof(grid_map_t_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 grid_map_t_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg grid_map_t LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int grid_map_t_subscription_set_queue_capacity (grid_map_t_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int grid_map_t_unsubscribe(lcm_t *lcm, grid_map_t_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe grid_map_t_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

